import type { Metadata } from "next";
import { Playfair_Display, Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/general/Header";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
});

const raleway = Raleway({
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} mt-18 ${raleway.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
